--- # Load balancer

- hosts: awstest
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars_files:
  - variables/apache2_variables.yml
  tasks:
    - include: packages/apache2.yml
    - include: commands/copy_apache_configs.yml
    - include: commands/set_apache_permissions.yml
    - include: handler/restart_apache.yml
    - include: commands/test_apache.yml
