--- # Load balancer

- hosts: strato
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars_files:
  - variables/apache2_variables.yml
  tasks:
    - include: packages/apache2.yml
    - include: tasks/copy_apache_configs.yml
    - include: tasks/enable_apache_mods.yml
    - include: tasks/set_apache_permissions.yml
    - include: handler/restart_apache.yml
    - include: tasks/test_apache.yml
